Add support for competitions
wise-old-man/helpful-old-man pull request #11
Opened 2024-09-18 20:43 UTC by not-geeving

2024-09-23 20:36 UTC, Jonxslays requested changes

2024-09-23 20:36 UTC, Jonxslays commented on hom/cogs/views.py
> -    "Verify",
can we get these back in alphabetical order?

2024-09-23 20:36 UTC, Jonxslays commented on hom/cogs/views.py
> +        label="Names",
"Name Changes" please

2024-09-24 04:12 UTC, not-geeving commented on hom/cogs/views.py
> -    "Verify",
yea, I just copied the order of classes since that's the order the persistent views were added in at the end of the file as well

2024-09-24 13:33 UTC, Jonxslays approved these changes

2024-10-05 15:56 UTC, merged